### ISSUE TITLE
Version of download manager to use

### ISSUE THREAD

**Issue by larrytech7** [vertragswecker/RxDownloadManager#2]
I can't seem to get the version of the download manager to use here. the variable $rxDownloadManager does not resolve here

**Comment by tynn** [comment]
Just replace it with the current version of this library or define it in your root _build.gradle_

    ext {
        rxDownloadManager = '0.1'
    }

**Comment by larrytech7** [comment]
Figured it out already, thanks. Please how can i prevent the download notification from showing. I need just a quite download and not that it should show in the notifications panel
